# Generated by Django 5.2.5 on 2025-08-31 19:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Phishing_Detection', '0002_alertnotification_alerttemplate_alter_alert_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisarmedLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_url', models.URLField()),
                ('safe_replacement', models.CharField(max_length=500)),
                ('disarm_method', models.CharField(choices=[('BLOCK', 'Blocked with warning'), ('SANITIZE', 'Sanitized URL'), ('REDIRECT', 'Safe redirect'), ('PLACEHOLDER', 'Text placeholder'), ('PREVIEW', 'Safe preview mode')], max_length=20)),
                ('disarm_reason', models.TextField()),
                ('click_attempts', models.IntegerField(default=0)),
                ('user_overridden', models.BooleanField(default=False)),
                ('override_reason', models.TextField(blank=True, null=True)),
                ('disarm_timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('threat_detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disarmed_links', to='Phishing_Detection.threatdetectionresult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disarmed_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-disarm_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProtectionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('rule_type', models.CharField(choices=[('URL_PATTERN', 'URL Pattern Blocking'), ('DOMAIN_WHITELIST', 'Domain Whitelist'), ('FILE_EXTENSION', 'File Extension Blocking'), ('SENDER_PATTERN', 'Sender Pattern Blocking'), ('CONTENT_KEYWORD', 'Content Keyword Blocking')], max_length=20)),
                ('pattern', models.TextField()),
                ('action', models.CharField(choices=[('BLOCK', 'Block completely'), ('WARN', 'Warn user'), ('QUARANTINE', 'Quarantine'), ('ALLOW', 'Allow')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=100)),
                ('times_triggered', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protection_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuarantinedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_hash', models.CharField(max_length=64, unique=True)),
                ('file_size', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('quarantine_location', models.CharField(max_length=500)),
                ('safe_preview_location', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('QUARANTINED', 'Quarantined'), ('ANALYZING', 'Under Analysis'), ('SAFE', 'Marked Safe'), ('MALICIOUS', 'Confirmed Malicious'), ('DELETED', 'Permanently Deleted')], default='QUARANTINED', max_length=20)),
                ('source_context', models.CharField(max_length=50)),
                ('quarantine_timestamp', models.DateTimeField(auto_now_add=True)),
                ('analysis_completed_at', models.DateTimeField(blank=True, null=True)),
                ('threat_detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarantined_files', to='Phishing_Detection.threatdetectionresult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarantined_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-quarantine_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RealTimeSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('EMAIL', 'Email Protection'), ('SMS', 'SMS Protection'), ('BROWSER', 'Browser Protection'), ('MOBILE', 'Mobile App Protection'), ('CHAT', 'Chat/Messaging Protection')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('threats_blocked', models.IntegerField(default=0)),
                ('links_disarmed', models.IntegerField(default=0)),
                ('files_quarantined', models.IntegerField(default=0)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protection_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ProtectionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('LINK_DISARMED', 'Link Disarmed'), ('FILE_QUARANTINED', 'File Quarantined'), ('THREAT_BLOCKED', 'Threat Blocked'), ('USER_OVERRIDE', 'User Override'), ('RULE_TRIGGERED', 'Protection Rule Triggered')], max_length=20)),
                ('description', models.TextField()),
                ('source_data', models.JSONField(default=dict)),
                ('result_data', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('disarmed_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='threat_protection.disarmedlink')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protection_logs', to=settings.AUTH_USER_MODEL)),
                ('protection_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='threat_protection.protectionrule')),
                ('quarantined_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='threat_protection.quarantinedfile')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='threat_protection.realtimesession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='disarmedlink',
            index=models.Index(fields=['user', 'disarm_timestamp'], name='threat_prot_user_id_a77c47_idx'),
        ),
        migrations.AddIndex(
            model_name='disarmedlink',
            index=models.Index(fields=['original_url'], name='threat_prot_origina_8dac4e_idx'),
        ),
        migrations.AddIndex(
            model_name='disarmedlink',
            index=models.Index(fields=['disarm_method'], name='threat_prot_disarm__808090_idx'),
        ),
        migrations.AddIndex(
            model_name='protectionrule',
            index=models.Index(fields=['user', 'is_active'], name='threat_prot_user_id_01d9c1_idx'),
        ),
        migrations.AddIndex(
            model_name='protectionrule',
            index=models.Index(fields=['rule_type', 'priority'], name='threat_prot_rule_ty_c1e1dc_idx'),
        ),
        migrations.AddIndex(
            model_name='quarantinedfile',
            index=models.Index(fields=['user', 'status'], name='threat_prot_user_id_0c4885_idx'),
        ),
        migrations.AddIndex(
            model_name='quarantinedfile',
            index=models.Index(fields=['file_hash'], name='threat_prot_file_ha_1660d1_idx'),
        ),
        migrations.AddIndex(
            model_name='quarantinedfile',
            index=models.Index(fields=['quarantine_timestamp'], name='threat_prot_quarant_39da6f_idx'),
        ),
        migrations.AddIndex(
            model_name='realtimesession',
            index=models.Index(fields=['user', 'is_active'], name='threat_prot_user_id_828a9a_idx'),
        ),
        migrations.AddIndex(
            model_name='realtimesession',
            index=models.Index(fields=['session_type', 'started_at'], name='threat_prot_session_bb7294_idx'),
        ),
        migrations.AddIndex(
            model_name='protectionlog',
            index=models.Index(fields=['user', 'timestamp'], name='threat_prot_user_id_8ea4cb_idx'),
        ),
        migrations.AddIndex(
            model_name='protectionlog',
            index=models.Index(fields=['action_type', 'timestamp'], name='threat_prot_action__5f3a36_idx'),
        ),
        migrations.AddIndex(
            model_name='protectionlog',
            index=models.Index(fields=['session', 'timestamp'], name='threat_prot_session_a3c3c4_idx'),
        ),
    ]
