// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGycwPxYtYyKere6xsbjuOik0QoxC-CCg',
    appId: '1:165846313594:web:b3a34f9ad062130720a9c3',
    messagingSenderId: '165846313594',
    projectId: 'phishzildevs',
    authDomain: 'phishzildevs.firebaseapp.com',
    storageBucket: 'phishzildevs.firebasestorage.app',
    measurementId: 'G-JVP1YEQRL2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7bssjE7SWY_jrLeXvzolW8zaEMwufV0w',
    appId: '1:165846313594:android:2a4c871a49a7ee8120a9c3',
    messagingSenderId: '165846313594',
    projectId: 'phishzildevs',
    storageBucket: 'phishzildevs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwA0SN2TPAn-IZZs8hRKhQZLUKs38VjUA',
    appId: '1:165846313594:ios:11757dc242ef73f520a9c3',
    messagingSenderId: '165846313594',
    projectId: 'phishzildevs',
    storageBucket: 'phishzildevs.firebasestorage.app',
    iosBundleId: 'com.example.phishzil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwA0SN2TPAn-IZZs8hRKhQZLUKs38VjUA',
    appId: '1:165846313594:ios:11757dc242ef73f520a9c3',
    messagingSenderId: '165846313594',
    projectId: 'phishzildevs',
    storageBucket: 'phishzildevs.firebasestorage.app',
    iosBundleId: 'com.example.phishzil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGycwPxYtYyKere6xsbjuOik0QoxC-CCg',
    appId: '1:165846313594:web:439af3841881d76220a9c3',
    messagingSenderId: '165846313594',
    projectId: 'phishzildevs',
    authDomain: 'phishzildevs.firebaseapp.com',
    storageBucket: 'phishzildevs.firebasestorage.app',
    measurementId: 'G-3D5Z4BQJPW',
  );
}
