# Generated by Django 5.2.5 on 2025-08-31 15:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('feed_type', models.CharField(choices=[('PHISHTANK', 'PhishTank'), ('OPENPHISH', 'OpenPhish'), ('URLVOID', 'URLVoid'), ('VIRUSTOTAL', 'VirusTotal'), ('CUSTOM', 'Custom Feed')], max_length=20)),
                ('url', models.URLField()),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('update_frequency', models.IntegerField(default=3600)),
                ('total_threats', models.IntegerField(default=0)),
                ('new_threats_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('PHISHING_URL', 'Phishing URL Detected'), ('MALICIOUS_FILE', 'Malicious File Detected'), ('SUSPICIOUS_EMAIL', 'Suspicious Email Content'), ('DOMAIN_SPOOFING', 'Domain Spoofing Attempt'), ('CREDENTIAL_HARVEST', 'Credential Harvesting Attempt'), ('SOCIAL_ENGINEERING', 'Social Engineering Detected')], max_length=30)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved'), ('FALSE_POSITIVE', 'False Positive')], default='ACTIVE', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('threat_details', models.JSONField(default=dict)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('source_file', models.CharField(blank=True, max_length=255, null=True)),
                ('source_content', models.TextField(blank=True, null=True)),
                ('user_override', models.BooleanField(default=False)),
                ('override_reason', models.TextField(blank=True, null=True)),
                ('override_timestamp', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SafeBrowsingWarning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_url', models.URLField()),
                ('warning_type', models.CharField(choices=[('PHISHING', 'Phishing Site'), ('MALWARE', 'Malware Distribution'), ('SUSPICIOUS', 'Suspicious Content'), ('BLOCKED', 'Blocked Domain')], max_length=20)),
                ('threat_details', models.JSONField(default=dict)),
                ('user_proceeded', models.BooleanField(default=False)),
                ('proceed_timestamp', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Phishing_Detection.alert')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreatDetectionResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('detection_type', models.CharField(choices=[('URL', 'URL Detection'), ('TEXT', 'Text/Message Detection'), ('FILE', 'File Detection')], max_length=10)),
                ('analyzed_url', models.URLField(blank=True, null=True)),
                ('analyzed_text', models.TextField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('is_malicious', models.BooleanField()),
                ('threat_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('confidence_score', models.FloatField()),
                ('threat_types', models.JSONField(default=list)),
                ('indicators', models.JSONField(default=list)),
                ('recommended_action', models.CharField(max_length=50)),
                ('analysis_details', models.JSONField(default=dict)),
                ('processing_time_ms', models.IntegerField(blank=True, null=True)),
                ('context', models.CharField(blank=True, max_length=20, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=50)),
                ('request_data_hash', models.CharField(max_length=64)),
                ('response_time_ms', models.IntegerField()),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('detection_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Phishing_Detection.threatdetectionresult')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='alert',
            name='detection_result',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert', to='Phishing_Detection.threatdetectionresult'),
        ),
        migrations.CreateModel(
            name='ThreatDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threat_type', models.CharField(choices=[('URL', 'Malicious URL'), ('DOMAIN', 'Malicious Domain'), ('HASH', 'File Hash'), ('PATTERN', 'Content Pattern'), ('IP', 'Malicious IP'), ('EMAIL', 'Known Phishing Email')], max_length=20)),
                ('value', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('tags', models.JSONField(default=list)),
                ('first_seen', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('confidence_score', models.FloatField(default=0.8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source_feed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Phishing_Detection.threatfeed')),
            ],
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('PHISHING_URL', 'Phishing URL'), ('PHISHING_EMAIL', 'Phishing Email'), ('MALICIOUS_FILE', 'Malicious File'), ('SPAM', 'Spam Content'), ('SCAM', 'Scam/Fraud'), ('OTHER', 'Other Threat')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('INVESTIGATING', 'Under Investigation'), ('CONFIRMED', 'Confirmed Threat'), ('FALSE_POSITIVE', 'False Positive'), ('DUPLICATE', 'Duplicate Report')], default='PENDING', max_length=20)),
                ('suspicious_url', models.URLField(blank=True, null=True)),
                ('suspicious_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('content_description', models.TextField()),
                ('source_context', models.CharField(blank=True, max_length=50, null=True)),
                ('threat_indicators', models.JSONField(default=list)),
                ('screenshots', models.JSONField(default=list)),
                ('automated_analysis', models.JSONField(blank=True, default=dict)),
                ('manual_review_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='threatdetectionresult',
            index=models.Index(fields=['is_malicious', 'threat_level'], name='Phishing_De_is_mali_11d532_idx'),
        ),
        migrations.AddIndex(
            model_name='threatdetectionresult',
            index=models.Index(fields=['detection_type', 'created_at'], name='Phishing_De_detecti_9e1c82_idx'),
        ),
        migrations.AddIndex(
            model_name='threatdetectionresult',
            index=models.Index(fields=['user', 'created_at'], name='Phishing_De_user_id_38964b_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['user', 'status', 'severity'], name='Phishing_De_user_id_b5e077_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['alert_type', 'created_at'], name='Phishing_De_alert_t_195c93_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['severity', 'status'], name='Phishing_De_severit_45ccf1_idx'),
        ),
        migrations.AddIndex(
            model_name='threatdatabase',
            index=models.Index(fields=['threat_type', 'value'], name='Phishing_De_threat__bb094d_idx'),
        ),
        migrations.AddIndex(
            model_name='threatdatabase',
            index=models.Index(fields=['severity'], name='Phishing_De_severit_e44ac5_idx'),
        ),
        migrations.AddIndex(
            model_name='threatdatabase',
            index=models.Index(fields=['source_feed', 'updated_at'], name='Phishing_De_source__5c3dde_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='threatdatabase',
            unique_together={('threat_type', 'value')},
        ),
        migrations.AddIndex(
            model_name='userreport',
            index=models.Index(fields=['user', 'status'], name='Phishing_De_user_id_7625e0_idx'),
        ),
        migrations.AddIndex(
            model_name='userreport',
            index=models.Index(fields=['report_type', 'status'], name='Phishing_De_report__5fe799_idx'),
        ),
        migrations.AddIndex(
            model_name='userreport',
            index=models.Index(fields=['created_at'], name='Phishing_De_created_358927_idx'),
        ),
    ]
