# Generated by Django 5.2.5 on 2025-08-31 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phishing_Detection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('EMAIL', 'Email'), ('PUSH', 'Push Notification'), ('SMS', 'SMS'), ('IN_APP', 'In-App Notification')], max_length=10)),
                ('recipient', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('READ', 'Read by User')], default='PENDING', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('alert_type', models.CharField(choices=[('PHISHING_URL', 'Phishing URL Detected'), ('MALICIOUS_FILE', 'Malicious File Detected'), ('SUSPICIOUS_EMAIL', 'Suspicious Email Content'), ('DOMAIN_SPOOFING', 'Domain Spoofing Attempt'), ('CREDENTIAL_HARVEST', 'Credential Harvesting Attempt'), ('SOCIAL_ENGINEERING', 'Social Engineering Detected')], max_length=30)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('title_template', models.CharField(max_length=200)),
                ('description_template', models.TextField()),
                ('available_variables', models.JSONField(default=list, help_text='List of available template variables like {url}, {confidence}, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-priority', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='threatfeed',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='threatdatabase',
            name='Phishing_De_severit_e44ac5_idx',
        ),
        migrations.AddField(
            model_name='alert',
            name='auto_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='escalation_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alert',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='notification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='priority',
            field=models.IntegerField(default=1, help_text='1=Highest, 5=Lowest'),
        ),
        migrations.AddField(
            model_name='alert',
            name='related_alerts',
            field=models.ManyToManyField(blank=True, to='Phishing_Detection.alert'),
        ),
        migrations.AddField(
            model_name='alert',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved'), ('FALSE_POSITIVE', 'False Positive'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='detectionlog',
            name='detection_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='Phishing_Detection.threatdetectionresult'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['is_read', 'created_at'], name='Phishing_De_is_read_34c147_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['priority', 'created_at'], name='Phishing_De_priorit_48d277_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['expires_at'], name='Phishing_De_expires_2e7445_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['auto_created'], name='Phishing_De_auto_cr_69a367_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['escalation_level'], name='Phishing_De_escalat_4c5ba6_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionlog',
            index=models.Index(fields=['endpoint', 'created_at'], name='Phishing_De_endpoin_1de9b4_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionlog',
            index=models.Index(fields=['request_data_hash'], name='Phishing_De_request_012b69_idx'),
        ),
        migrations.AddIndex(
            model_name='safebrowsingwarning',
            index=models.Index(fields=['original_url'], name='Phishing_De_origina_f39949_idx'),
        ),
        migrations.AddIndex(
            model_name='safebrowsingwarning',
            index=models.Index(fields=['user', 'created_at'], name='Phishing_De_user_id_e646f0_idx'),
        ),
        migrations.AddIndex(
            model_name='safebrowsingwarning',
            index=models.Index(fields=['warning_type'], name='Phishing_De_warning_cd98b9_idx'),
        ),
        migrations.AddIndex(
            model_name='safebrowsingwarning',
            index=models.Index(fields=['user_proceeded'], name='Phishing_De_user_pr_a9f08c_idx'),
        ),
        migrations.AddIndex(
            model_name='threatdatabase',
            index=models.Index(fields=['severity', 'is_active'], name='Phishing_De_severit_974074_idx'),
        ),
        migrations.AddIndex(
            model_name='threatdatabase',
            index=models.Index(fields=['is_active', 'threat_type'], name='Phishing_De_is_acti_ff956f_idx'),
        ),
        migrations.AddIndex(
            model_name='threatdetectionresult',
            index=models.Index(fields=['file_hash'], name='Phishing_De_file_ha_0d8aca_idx'),
        ),
        migrations.AddIndex(
            model_name='threatdetectionresult',
            index=models.Index(fields=['confidence_score'], name='Phishing_De_confide_fe2568_idx'),
        ),
        migrations.AddIndex(
            model_name='threatfeed',
            index=models.Index(fields=['feed_type', 'is_active'], name='Phishing_De_feed_ty_46b50a_idx'),
        ),
        migrations.AddIndex(
            model_name='threatfeed',
            index=models.Index(fields=['last_updated'], name='Phishing_De_last_up_dd90e5_idx'),
        ),
        migrations.AddIndex(
            model_name='userreport',
            index=models.Index(fields=['status', 'reviewed_at'], name='Phishing_De_status_e6dfcc_idx'),
        ),
        migrations.AddIndex(
            model_name='userreport',
            index=models.Index(fields=['suspicious_url'], name='Phishing_De_suspici_692a9a_idx'),
        ),
        migrations.AddField(
            model_name='alertnotification',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Phishing_Detection.alert'),
        ),
        migrations.AddIndex(
            model_name='alerttemplate',
            index=models.Index(fields=['alert_type', 'severity'], name='Phishing_De_alert_t_221d50_idx'),
        ),
        migrations.AddIndex(
            model_name='alerttemplate',
            index=models.Index(fields=['is_active'], name='Phishing_De_is_acti_fc849a_idx'),
        ),
        migrations.AddIndex(
            model_name='alerttemplate',
            index=models.Index(fields=['name'], name='Phishing_De_name_4df569_idx'),
        ),
        migrations.AddIndex(
            model_name='alertnotification',
            index=models.Index(fields=['alert', 'notification_type'], name='Phishing_De_alert_i_bd0aa4_idx'),
        ),
        migrations.AddIndex(
            model_name='alertnotification',
            index=models.Index(fields=['status', 'created_at'], name='Phishing_De_status_6749b0_idx'),
        ),
        migrations.AddIndex(
            model_name='alertnotification',
            index=models.Index(fields=['recipient'], name='Phishing_De_recipie_c47dbf_idx'),
        ),
    ]
