name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD_FRONTEND }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME_FRONTEND }}" --password-stdin

      - name: Build Docker image
        run: docker build -t francis3610/phishzil-frontend:latest .

      - name: Push Docker image
        run: docker push francis3610/phishzil-frontend:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull francis3610/phishzil-frontend:latest
            docker stop phishzil-frontend || true
            docker rm phishzil-frontend || true
            docker run -d --name phishzil-frontend -p 80:80 francis3610/phishzil-frontend:latest
